作業目標
活用矩陣運算，實做線性代數
作業重點
線性代數公式應用
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:
array1 = np.array([[10, 8], [3, 5]]) 
運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
運用上列array計算特徵值、特徵向量?
運用上列array計算SVD?

In [3]:
import numpy as np

In [5]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
array1_inv = np.linalg.inv(array1)
np.dot(array1_inv,array1)

array([[1.00000000e+00, 5.55111512e-17],
       [0.00000000e+00, 1.00000000e+00]])

In [8]:
#2. 運用上列array計算特徵值、特徵向量?
array1 = np.array([[10, 8], [3, 5]])
ev,evt = np.linalg.eig(array1)
ev#特徵值

array([13.,  2.])

In [9]:
evt#特徵值向量

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [12]:
#3. 運用上列array計算SVD?
u, s, vh = np.linalg.svd(array1)
(u,s,vh)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))